FROM node:lts-alpine3.14
ENV DIR=/usr/src/dehub-gui
RUN mkdir -p $DIR
WORKDIR $DIR
RUN apk update && apk upgrade && apk add git
COPY . $DIR
RUN npm install && npm audit fix && npm run build
EXPOSE 3000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
CMD [ "npm", "run", "dev" ]
